version: '3'

services:
  keycloak:
    image: agnos-keycloak:1.0
    container_name: agnos-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin2357
      KC_HTTP_RELATIVE_PATH: "/auth"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_URL: "${KEYCLOAK_PUBLIC_IP}:${KEYCLOAK_PUBLIC_PORT}/auth/"
      KEYCLOAK_FRONTEND_URL: "${KEYCLOAK_PUBLIC_IP}:${KEYCLOAK_PUBLIC_PORT}/auth/realms/AgnosRealm"
    networks:
      - keycloak
    depends_on:
      - nginx
    ports:
      - "${KEYCLOAK_PUBLIC_PORT}:8080"
    restart: always
    volumes:
      - /home/ruzsaz/IdeaProjects/Agnos/AgnosKeyCloack/local/keycloak/:/opt/keycloak/data/

  nginx:
    image: agnos-cube-nginx:1.0
    container_name: agnos-cube-nginx
    networks:
      - backend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  cube-server-1:
    image: agnos-cube-server:2.0
    container_name: agnos-cube-server-1
    volumes:
      - ${CUBES_DIR}:/usr/local/agnos/Cubes/
    networks:
      - backend
    expose:
      - 7979
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  cube-server-2:
    image: agnos-cube-server:2.0
    container_name: agnos-cube-server-2
    volumes:
      - ${CUBES_DIR}:/usr/local/agnos/Cubes/
    networks:
      - backend
    expose:
      - 7979
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  agnos-httpd:
    image: agnos-apache:2.4
    container_name: agnos-frontend
    environment:
      KEYCLOAK_PUBLIC_IP: "${KEYCLOAK_PUBLIC_IP}"
      KEYCLOAK_PUBLIC_PORT: "${KEYCLOAK_PUBLIC_PORT}"
      REPORTSERVER_PUBLIC_IP: "${REPORTSERVER_PUBLIC_IP}"
      REPORTSERVER_PUBLIC_PORT: "${REPORTSERVER_PUBLIC_PORT}"
    ports:
      - "8080:80"
    networks:
      - frontend
      - keycloak
    depends_on:
      - keycloak
      - report-server
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  report-server:
    image: agnos-report-server:2.0
    container_name: agnos-report-server
    environment:
      KEYCLOAK_INTERNAL_REALM_URI: "${KEYCLOAK_PUBLIC_IP}:${KEYCLOAK_PUBLIC_PORT}/auth/realms/AgnosRealm"
      CUBE_INTERNAL_IP: agnos-cube-nginx
    ports:
      - "${REPORTSERVER_PUBLIC_PORT}:9091"
    networks:
      - frontend
      - backend
      - keycloak
    depends_on:
      - nginx
      - keycloak
    restart: always
    volumes:
      - /home/ruzsaz/Agnos/Products/:/usr/local/agnos/Products/
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

networks:
  backend:
  frontend:
  keycloak:
