version: '3'

services:
  keycloak:
    image: ruzsaz/agnos-keycloak:4.0
    container_name: agnos-keycloak
    environment:
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
      KC_HTTP_RELATIVE_PATH: "${KEYCLOAK_PATH_PREFIX}"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_URL: "${KEYCLOAK_PUBLIC_IP}${KEYCLOAK_PATH_PREFIX}/"
      KC_HOSTNAME_ADMIN_URL: "${KEYCLOAK_PUBLIC_IP}${KEYCLOAK_PATH_PREFIX}/"
      KC_PROXY: "${KEYCLOAK_PROXY_MODE}"
      KEYCLOAK_FRONTEND_URL: "${KEYCLOAK_PUBLIC_IP}${KEYCLOAK_PATH_PREFIX}/realms/${KEYCLOAK_REALM}"
      KEYCLOAK_REALM: "${KEYCLOAK_REALM}"
      KEYCLOAK_CLIENT: "${KEYCLOAK_CLIENT}"
      REDIRECT_URIS: "\"${AGNOS_PUBLIC_IP}/*\", \"${REPORTMANAGER_PUBLIC_IP}/*\", \"${REPORTMANAGER_INSIDE_IP}/*\""
      KEYCLOAK_COMMAND_ARG: "start-dev"
    networks:
      - keycloak
    depends_on:
      - nginx
    ports:
      - "${KEYCLOAK_INSIDE_PORT}:8080"
    restart: always
    volumes:
      - "${KEYCLOAK_DATABASE_DIR}:/opt/keycloak/data/"

  nginx:
    image: ruzsaz/agnos-cube-nginx:4.0
    container_name: agnos-cube-nginx
    networks:
      - backend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  cube-server-1:
    image: ruzsaz/agnos-cube-server:4.0
    container_name: agnos-cube-server-1
    volumes:
      - "${CUBES_DIR}:/usr/local/agnos/Cubes/"
    networks:
      - backend
    expose:
      - 7979
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  cube-server-2:
    image: ruzsaz/agnos-cube-server:4.0
    container_name: agnos-cube-server-2
    volumes:
      - "${CUBES_DIR}:/usr/local/agnos/Cubes/"
    networks:
      - backend
    expose:
      - 7979
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  agnos-httpd:
    image: ruzsaz/agnos-apache:4.0
    container_name: agnos-frontend
    environment:
      KEYCLOAK_PUBLIC_IP: "${KEYCLOAK_PUBLIC_IP}"
      REPORTSERVER_PUBLIC_IP: "${REPORTSERVER_PUBLIC_IP}"
    ports:
      - "${AGNOS_INSIDE_PORT}:80"
    networks:
      - frontend
      - keycloak
    depends_on:
      - keycloak
      - report-server
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  report-server:
    image: ruzsaz/agnos-report-server:4.0
    container_name: agnos-report-server
    environment:
      KEYCLOAK_REALM_PUBLIC_URI: "${KEYCLOAK_PUBLIC_IP}${KEYCLOAK_PATH_PREFIX}/realms/${KEYCLOAK_REALM}"
      CUBE_INTERNAL_IP: agnos-cube-nginx
      CORS_ORIGINS: "${AGNOS_PUBLIC_IP}"
    ports:
      - "${REPORTSERVER_INSIDE_PORT}:9091"
    networks:
      - frontend
      - backend
      - keycloak
    depends_on:
      - nginx
      - keycloak
    restart: always
    volumes:
      - "${REPORTS_DIR}:/usr/local/agnos/Reports"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  report-manager:
    image: ruzsaz/agnos-report-manager:4.0
    container_name: agnos-report-manager
    environment:
      CUBE_SERVER_URI: "http://agnos-cube-nginx:7979/acs"
      REPORT_SERVER_URI: "http://agnos-report-server:9091/ars"
      KEYCLOAK_SERVERURL: "${KEYCLOAK_PUBLIC_IP}${KEYCLOAK_PATH_PREFIX}"
      KEYCLOAK_REALM: "${KEYCLOAK_REALM}"
      KEYCLOAK_CLIENTID: "${KEYCLOAK_CLIENT}"
      KEYCLOAK_REALM_PUBLIC_URI: "${KEYCLOAK_PUBLIC_IP}${KEYCLOAK_PATH_PREFIX}/realms/${KEYCLOAK_REALM}"
      KEYCLOAK_USERNAME: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
    ports:
      - "${REPORTMANAGER_INSIDE_PORT}:8080"
    networks:
      - backend
      - keycloak
    depends_on:
      - nginx
      - keycloak
    restart: always
    volumes:
      - "${REPORTS_DIR}:/opt/agnos/Reports"
      - "${CUBES_DIR}:/opt/agnos/Cubes"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"


networks:
  backend:
  frontend:
  keycloak:
