version: '3.3'

services:
  logspout:
    image: gliderlabs/logspout:v3
    labels:
      - "logspout.exclude=true"
    environment:
      - EXCLUDE_LABEL=logspout.exclude
      - LOGSPOUT=ignore
    command: 'udp://logstash:5000'
    links:
      - logstash
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    depends_on:
      - logstash

  logstash:
    image: ruzsaz/agnos-logstash:1.0
    labels:
      - "logspout.exclude=true"
    environment:
      - STDOUT=true
      - LOGSPOUT=ignore
    volumes:
      - "${LOG_FILES_DIRECTORY}:/usr/share/logstash/data/agnos"
